from fabulist.controllers.BaseController import BaseController
from fabulist.controllers.ActivityController import ActivityController
from fabulist.controllers.AssistantController import AssistantController
from fabulist.controllers.AuthorController import AuthorController
from fabulist.controllers.BibliographyController import BibliographyController
from fabulist.controllers.ChapterController import ChapterController
from fabulist.controllers.CharacterController import CharacterController
from fabulist.controllers.EventController import EventController
from fabulist.controllers.ExportController import ExportController
from fabulist.controllers.ImageController import ImageController
from fabulist.controllers.LinkController import LinkController
from fabulist.controllers.LocationController import LocationController
from fabulist.controllers.NoteController import NoteController
from fabulist.controllers.OllamaModelController import OllamaModelController
from fabulist.controllers.SceneController import SceneController
from fabulist.controllers.StoryController import StoryController
from fabulist.controllers.SubmissionController import SubmissionController
from fabulist.controllers.UserController import UserController





